services:
  python:
    image: scraper/python
    container_name: "scraper-python"
    build:
      context: .
      dockerfile: ./Dockerfile
  chrome:
    image: selenium/standalone-chrome:125.0
    container_name: "chrome"
    ports:
      - 4444:4444
      - 7900:7900
